=== kkoruev/learning-code/fmi_xml/library.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Library (publishing_houses, books, authors)>
	<!ELEMENT publishing_houses (publishing_house)+ >
		<!ELEMENT publishing_house (publishing_house_name, year, address, email)>
		<!ATTLIST publishing_house publishing_house_id ID #REQUIRED>
		<!ELEMENT publishing_house_name (#PCDATA)>
		<!ELEMENT year (#PCDATA)>		
		<!ELEMENT address (#PCDATA)>
		<!ELEMENT email (#PCDATA)>
	<!ELEMENT books (book)+>
		<!ELEMENT book (book_title, pages, genre, language)>
		<!ATTLIST book book_id ID #REQUIRED>
		<!ATTLIST book publishing_house_id IDREF #REQUIRED>
		<!ATTLIST book author_id IDREF #REQUIRED>
		<!ELEMENT book_title (#PCDATA)>
		<!ELEMENT pages (#PCDATA)>
		<!ELEMENT genre (#PCDATA)>
		<!ELEMENT language (#PCDATA)>
	<!ELEMENT authors (author)+>
		<!ELEMENT author (name, email, nationality, gender, age)>
		<!ATTLIST author author_id ID #REQUIRED>
		<!ELEMENT name (first_name, last_name)>
		<!ELEMENT first_name (#PCDATA)>
		<!ELEMENT last_name (#PCDATA)>
		<!ELEMENT nationality (#PCDATA)>
		<!ELEMENT gender (#PCDATA)>
		<!ELEMENT age (#PCDATA)>

=== kkoruev/learning-code/fmi_xml/library_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Library SYSTEM "library.dtd" >
<Library>
    <publishing_houses>

        <publishing_house publishing_house_id="ph11">
            <publishing_house_name>Glass Press</publishing_house_name>
            <year>1980</year>
            <address>Chicago, st Picadily 15</address>
            <email>glass@gmail.com</email>
        </publishing_house>

        <publishing_house publishing_house_id="ph12">
            <publishing_house_name>Golden Lions</publishing_house_name>
            <year>2004</year>
            <address>Sofia, st Maria Luiza 38</address>
            <email>goldenlions@gmail.com</email>
        </publishing_house>

    </publishing_houses>

    <books>

        <book book_id="b1" publishing_house_id="ph12" author_id="a1">
            <book_title>The Ballad of Les Darcy</book_title>
            <pages>397</pages>
            <genre>Biography</genre>
            <language>English</language>
        </book>

	<book book_id="b2" publishing_house_id="ph12" author_id="a2">
            <book_title>A Woman's War</book_title>
            <pages>229</pages>
            <genre>History </genre>
            <language>English</language>
        </book>
	
	<book book_id="b3" publishing_house_id="ph11" author_id="a3">
            <book_title>Errata</book_title>
            <pages>156</pages>
            <genre>Poetry</genre>
            <language>French</language>
        </book>

	<book book_id="b4" publishing_house_id="ph12" author_id="a4">
            <book_title>Gateway to Fourline</book_title>
            <pages>245</pages>
            <genre>Fantasy</genre>
            <language>English</language>
        </book>

	<book book_id="b5" publishing_house_id="ph11" author_id="a5">
            <book_title>Battling the Gods</book_title>
            <pages>356</pages>
            <genre>Philosophy</genre>
            <language>English</language>
        </book>
	
	<book book_id="b6" publishing_house_id="ph12" author_id="a6">
            <book_title>East of the Sun</book_title>
            <pages>368</pages>
            <genre>Art</genre>
            <language>English</language>
        </book>

	<book book_id="b7" publishing_house_id="ph11" author_id="a7">
            <book_title>Walking Heartbreak</book_title>
            <pages>238</pages>
            <genre>Music</genre>
            <language>English</language>
        </book>

	<book book_id="b8" publishing_house_id="ph11" author_id="a8">
            <book_title>Thing Explainer</book_title>
            <pages>435</pages>
            <genre>Science</genre>
            <language>English</language>
        </book>

    </books>

    <authors>

        <author author_id="a1">
            <name>
                <first_name>Peter</first_name>
                <last_name>Fitz</last_name>
            </name>
            <email>fitz_pet@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>41</age>
        </author>

        <author author_id="a2">
            <name>
                <first_name>Herman</first_name>
                <last_name>Wouk</last_name>
            </name>
            <email>wouk.n@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>62</age>
        </author>

        <author author_id="a3">
            <name>
                <first_name>Lisa</first_name>
                <last_name>Coutley</last_name>
            </name>
            <email>coutley.lisa@guen.fr</email>
            <nationality>French</nationality>
            <gender>Female</gender>
            <age>34</age>
        </author>

        <author author_id="a4">
            <name>
                <first_name>Pam</first_name>
                <last_name>Brondos</last_name>
            </name>
            <email>brondosgroup@abv.bg</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>46</age>
        </author>

        <author author_id="a5">
            <name>
                <first_name>Tim</first_name>
                <last_name>Whitmarsh</last_name>
            </name>
            <email>catapano.p@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>57</age>
        </author>

        <author author_id="a6">
            <name>
                <first_name>Noel</first_name>
                <last_name>Daniel</last_name>
            </name>
            <email>noel.daniel@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>28</age>
        </author>

        <author author_id="a7">
            <name>
                <first_name>Sunniva</first_name>
                <last_name>Dee</last_name>
            </name>
            <email>dee_h@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>24</age>
        </author>

        <author author_id="a8">
            <name>
                <first_name>Randall</first_name>
                <last_name>Torn</last_name>
            </name>
            <email>randall_t@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>46</age>
        </author>


    </authors>
</Library>

=== kkoruev/learning-code/fmi_xml/library_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Library SYSTEM "library.dtd" >
<Library>
    <publishing_houses>

        <publishing_house publishing_house_id="ph1">
            <publishing_house_name>Drama Press</publishing_house_name>
            <year>1980</year>
            <address>New York, st York 27</address>
            <email>drama@gmail.com</email>
        </publishing_house>

        <publishing_house publishing_house_id="ph2">
            <publishing_house_name>Big</publishing_house_name>
            <year>2004</year>
            <address>Sofia, st Makedonia 38</address>
            <email>big@gmail.com</email>
        </publishing_house>

        <publishing_house publishing_house_id="ph3">
            <publishing_house_name>Role Press</publishing_house_name>
            <year>1950</year>
            <address>Paris, st Gue Poe 12</address>
            <email>role_press@goloe.fr</email>
        </publishing_house>

        <publishing_house publishing_house_id="ph4">
            <publishing_house_name>Brute Force</publishing_house_name>
            <year>2009</year>
            <address>London, st Chelsea 12</address>
            <email>force@yahoo.com</email>
        </publishing_house>

    </publishing_houses>

    <books>

        <book book_id="b1" publishing_house_id="ph1" author_id="a1">
            <book_title>The Ballad of Les Darcy</book_title>
            <pages>399</pages>
            <genre>Biography</genre>
            <language>English</language>
        </book>

	<book book_id="b2" publishing_house_id="ph3" author_id="a2">
            <book_title>A History of Ukraine</book_title>
            <pages>229</pages>
            <genre>History </genre>
            <language>Ukrainian</language>
        </book>
	
	<book book_id="b3" publishing_house_id="ph2" author_id="a3">
            <book_title>La Douleur Exquise</book_title>
            <pages>156</pages>
            <genre>Poetry</genre>
            <language>French</language>
        </book>

	<book book_id="b4" publishing_house_id="ph4" author_id="a4">
            <book_title>Shadow's End</book_title>
            <pages>245</pages>
            <genre>Fantasy</genre>
            <language>English</language>
        </book>

	<book book_id="b5" publishing_house_id="ph3" author_id="a5">
            <book_title>The Big Think Book</book_title>
            <pages>356</pages>
            <genre>Philosophy</genre>
            <language>English</language>
        </book>
	
	<book book_id="b6" publishing_house_id="ph4" author_id="a6">
            <book_title>The Anatomical Shape of a Heart</book_title>
            <pages>368</pages>
            <genre>Art</genre>
            <language>English</language>
        </book>

	<book book_id="b7" publishing_house_id="ph1" author_id="a7">
            <book_title>Young Widows Club</book_title>
            <pages>238</pages>
            <genre>Music</genre>
            <language>English</language>
        </book>

	<book book_id="b8" publishing_house_id="ph2" author_id="a8">
            <book_title>The Old Man and the Sea</book_title>
            <pages>435</pages>
            <genre>Classic</genre>
            <language>English</language>
        </book>

    </books>

    <authors>

        <author author_id="a1">
            <name>
                <first_name>James</first_name>
                <last_name>Coburn</last_name>
            </name>
            <email>j.c.books@gmail.bg</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>41</age>
        </author>

        <author author_id="a2">
            <name>
                <first_name>Serhii</first_name>
                <last_name>Plokhy</last_name>
            </name>
            <email>serhii11@gmail.bg</email>
            <nationality>Polish</nationality>
            <gender>Male</gender>
            <age>62</age>
        </author>

        <author author_id="a3">
            <name>
                <first_name>John</first_name>
                <last_name>Rogue</last_name>
            </name>
            <email>j.rogue@abv.bg</email>
            <nationality>French</nationality>
            <gender>Male</gender>
            <age>34</age>
        </author>

        <author author_id="a4">
            <name>
                <first_name>Thea</first_name>
                <last_name>Harrison</last_name>
            </name>
            <email>t_har@abv.bg</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>46</age>
        </author>

        <author author_id="a5">
            <name>
                <first_name>Peter</first_name>
                <last_name>Cave</last_name>
            </name>
            <email>peter_c@abv.bg</email>
            <nationality>Australian</nationality>
            <gender>Male</gender>
            <age>57</age>
        </author>

        <author author_id="a6">
            <name>
                <first_name>Jenn</first_name>
                <last_name>Bennett</last_name>
            </name>
            <email>jenny_b@abv.bg</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>28</age>
        </author>

        <author author_id="a7">
            <name>
                <first_name>Alexandra</first_name>
                <last_name>Coutts</last_name>
            </name>
            <email>alex.co@abv.bg</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>19</age>
        </author>

        <author author_id="a8">
            <name>
                <first_name>Ernest</first_name>
                <last_name>Hemingway</last_name>
            </name>
            <email>hemingway@gmail.bg</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>68</age>
        </author>


    </authors>
</Library>

=== kkoruev/learning-code/fmi_xml/library_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Library SYSTEM "library.dtd" >
<Library>
    <publishing_houses>

        <publishing_house publishing_house_id="ph7">
            <publishing_house_name>Horror Press</publishing_house_name>
            <year>1980</year>
            <address>New Jersey, st Dwark 15</address>
            <email>horror@gmail.com</email>
        </publishing_house>

        <publishing_house publishing_house_id="ph8">
            <publishing_house_name>Medium</publishing_house_name>
            <year>2004</year>
            <address>Sofia, st Ignatiev 38</address>
            <email>Medium@gmail.com</email>
        </publishing_house>

    </publishing_houses>

    <books>

        <book book_id="b1" publishing_house_id="ph8" author_id="a1">
            <book_title>The Bassoon King</book_title>
            <pages>397</pages>
            <genre>Biography</genre>
            <language>English</language>
        </book>

	<book book_id="b2" publishing_house_id="ph8" author_id="a2">
            <book_title>Lee Miller: A Woman's War</book_title>
            <pages>229</pages>
            <genre>History </genre>
            <language>English</language>
        </book>
	
	<book book_id="b3" publishing_house_id="ph7" author_id="a3">
            <book_title>Nueve monedas</book_title>
            <pages>156</pages>
            <genre>Poetry</genre>
            <language>French</language>
        </book>

	<book book_id="b4" publishing_house_id="ph8" author_id="a4">
            <book_title>Ashley Bell</book_title>
            <pages>245</pages>
            <genre>Fantasy</genre>
            <language>English</language>
        </book>

	<book book_id="b5" publishing_house_id="ph7" author_id="a5">
            <book_title>The Stone Reader</book_title>
            <pages>356</pages>
            <genre>Philosophy</genre>
            <language>Italian</language>
        </book>
	
	<book book_id="b6" publishing_house_id="ph8" author_id="a6">
            <book_title>The Little Book of Vargas</book_title>
            <pages>368</pages>
            <genre>Art</genre>
            <language>English</language>
        </book>

	<book book_id="b7" publishing_house_id="ph7" author_id="a7">
            <book_title>For the Record </book_title>
            <pages>238</pages>
            <genre>Music</genre>
            <language>English</language>
        </book>

	<book book_id="b8" publishing_house_id="ph7" author_id="a8">
            <book_title>Ten Billion Tomorrows</book_title>
            <pages>435</pages>
            <genre>Science</genre>
            <language>English</language>
        </book>

    </books>

    <authors>

        <author author_id="a1">
            <name>
                <first_name>Rainn</first_name>
                <last_name>Wilson</last_name>
            </name>
            <email>wilson@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>41</age>
        </author>

        <author author_id="a2">
            <name>
                <first_name>Hilary</first_name>
                <last_name>Roberts</last_name>
            </name>
            <email>roberts.n@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>62</age>
        </author>

        <author author_id="a3">
            <name>
                <first_name>Carlos</first_name>
                <last_name>Pintado</last_name>
            </name>
            <email>pintado@guen.fr</email>
            <nationality>French</nationality>
            <gender>Male</gender>
            <age>34</age>
        </author>

        <author author_id="a4">
            <name>
                <first_name>Dean</first_name>
                <last_name>Koontz</last_name>
            </name>
            <email>koontzgroup@abv.bg</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>46</age>
        </author>

        <author author_id="a5">
            <name>
                <first_name>Peter</first_name>
                <last_name>Catapano</last_name>
            </name>
            <email>catapano.p@yahoo.com</email>
            <nationality>Italian</nationality>
            <gender>Male</gender>
            <age>57</age>
        </author>

        <author author_id="a6">
            <name>
                <first_name>Dian</first_name>
                <last_name>Hanson</last_name>
            </name>
            <email>hansonsed@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>28</age>
        </author>

        <author author_id="a7">
            <name>
                <first_name>Charlotte</first_name>
                <last_name>Huang</last_name>
            </name>
            <email>chatlotte_h@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>24</age>
        </author>

        <author author_id="a8">
            <name>
                <first_name>Brian</first_name>
                <last_name>Clegg</last_name>
            </name>
            <email>brian.clegg@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>46</age>
        </author>


    </authors>
</Library>

=== kkoruev/learning-code/fmi_xml/library_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Library SYSTEM "library.dtd" >
<Library>
    <publishing_houses>

        <publishing_house publishing_house_id="ph5">
            <publishing_house_name>Action Press</publishing_house_name>
            <year>1980</year>
            <address>New York, st Dwark 15</address>
            <email>action@gmail.com</email>
        </publishing_house>

        <publishing_house publishing_house_id="ph6">
            <publishing_house_name>Small</publishing_house_name>
            <year>2004</year>
            <address>Sofia, st Garibaldi 38</address>
            <email>small@gmail.com</email>
        </publishing_house>

    </publishing_houses>

    <books>

        <book book_id="b1" publishing_house_id="ph6" author_id="a1">
            <book_title>Drawing Blood</book_title>
            <pages>399</pages>
            <genre>Biography</genre>
            <language>English</language>
        </book>

	<book book_id="b2" publishing_house_id="ph6" author_id="a2">
            <book_title>First Bite</book_title>
            <pages>229</pages>
            <genre>History </genre>
            <language>English</language>
        </book>
	
	<book book_id="b3" publishing_house_id="ph5" author_id="a3">
            <book_title>The Paris Review Issue 215</book_title>
            <pages>156</pages>
            <genre>Poetry</genre>
            <language>French</language>
        </book>

	<book book_id="b4" publishing_house_id="ph6" author_id="a4">
            <book_title>Frozen Tides</book_title>
            <pages>245</pages>
            <genre>Fantasy</genre>
            <language>English</language>
        </book>

	<book book_id="b5" publishing_house_id="ph5" author_id="a5">
            <book_title>Fighting God</book_title>
            <pages>356</pages>
            <genre>Philosophy</genre>
            <language>English</language>
        </book>
	
	<book book_id="b6" publishing_house_id="ph6" author_id="a6">
            <book_title>Asia in Amsterdam</book_title>
            <pages>368</pages>
            <genre>Art</genre>
            <language>Japanese</language>
        </book>

	<book book_id="b7" publishing_house_id="ph5" author_id="a7">
            <book_title>Boys in the Trees</book_title>
            <pages>238</pages>
            <genre>Music</genre>
            <language>English</language>
        </book>

	<book book_id="b8" publishing_house_id="ph5" author_id="a8">
            <book_title>The Story Without an End</book_title>
            <pages>435</pages>
            <genre>Classic</genre>
            <language>English</language>
        </book>

    </books>

    <authors>

        <author author_id="a1">
            <name>
                <first_name>Molly</first_name>
                <last_name>Crabapple</last_name>
            </name>
            <email>molly.crbooks@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>41</age>
        </author>

        <author author_id="a2">
            <name>
                <first_name>Bee</first_name>
                <last_name>Wilson</last_name>
            </name>
            <email>wilsons.en@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>62</age>
        </author>

        <author author_id="a3">
            <name>
                <first_name>Lorin</first_name>
                <last_name>Stein</last_name>
            </name>
            <email>lorin_books@guen.fr</email>
            <nationality>French</nationality>
            <gender>Male</gender>
            <age>34</age>
        </author>

        <author author_id="a4">
            <name>
                <first_name>Morgan</first_name>
                <last_name>Rhodes</last_name>
            </name>
            <email>rhodesshouse@abv.bg</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>46</age>
        </author>

        <author author_id="a5">
            <name>
                <first_name>David</first_name>
                <last_name>Silverman</last_name>
            </name>
            <email>david_s@yahoo.com</email>
            <nationality>Australian</nationality>
            <gender>Male</gender>
            <age>57</age>
        </author>

        <author author_id="a6">
            <name>
                <first_name>Jan van</first_name>
                <last_name>Campen</last_name>
            </name>
            <email>campen.j@yahoo.com</email>
            <nationality>Japanese</nationality>
            <gender>Male</gender>
            <age>28</age>
        </author>

        <author author_id="a7">
            <name>
                <first_name>Carly</first_name>
                <last_name>Simon</last_name>
            </name>
            <email>carlies@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Male</gender>
            <age>24</age>
        </author>

        <author author_id="a8">
            <name>
                <first_name>Sarah</first_name>
                <last_name>Austin</last_name>
            </name>
            <email>austinsar@yahoo.com</email>
            <nationality>American</nationality>
            <gender>Female</gender>
            <age>46</age>
        </author>


    </authors>
</Library>
